### PR TITLE
Update CodeIgniter, Adapt Myth and Fix

### PR DESCRIPTION
**Pull request by ggallon**
Hello,
**CodeIgniter**: It's the last Update to CodeIgniter Commit on Jan 23, 2015, execpt that commit https://github.com/bcit-ci/CodeIgniter/commit/db669f1de59f7105e0b9cf39899b98fd75b90771 (Make libraries matching controller names loadable), because he breaks the Travis test (https://travis-ci.org/dev-ggallon/Sprint/jobs/47909498) : `PHP Fatal error:  Cannot redeclare class MY_Form_validation in /home/travis/build/dev-ggallon/Sprint/application/libraries/MY_Form_validation.php on line 110`.
If you have an idea of collision or incompatibility, I take it!!

**Myth**: Adaptation for working with the new session library
- Myth\Auth\LocalAuthentication
- Module Auth Controllers
- Controllers/Demos/Ajax
- Controllers/Demos/Layout
- Update Database/Migration/CreateSessionTable

**Myth**: Fix
- broken links for the Foundation Theme
- Notice display to renderJSON method and add missing notice view

enjoy

### CODE REVIEW

**Comment by lonnieezell** [comment]
I only had the one question regarding the notice view: https://github.com/dev-ggallon/Sprint/commit/f45c5d5c2a136ade951cd9699e1e247545bfa87b 

The rest looks great. Thanks! 

As for the My_Form_validition, I'm not sure, but I wouldn't be surprised if it has something to do with the HMVC loader needing to be updated for that. I'll try to take a look tonight.

**Comment by lonnieezell** [comment]
As far as I can tell, the  MY_Form_validation issue was only appearing during testing where one of the tests would load the library somehow (and I still don't know where it was getting loaded) before the auth tests ran that all used it also. Wrapping the My_Form_validation class if a simple class_exists check solved the issue. 

I've integrated that commit now so I think we're current.

**Comment by mwhitneysdsu** [comment]
The MY_Form_validation issue definitely sounds like a problem with the loader (or is a test bypassing the loader for some reason?). Wrapping the class in a check like that can work in the short term, but it's going to keep haunting you if the loader isn't checking this properly itself.

**Comment by lonnieezell** [comment]
That's what I thought at first, also, but haven't seen seen it recreated when exploring the existing functionality, and the tests all work separately. Even running all of the Auth-related tests together work. It's only when they're run right after the other tests in the whole project. 

I ran into something similar early on in the testing, but I don't remember exactly what now. It did have a similar issue, though that was only caused by how it was being tested and the fact that CI's singleton was not designed to have multiple instances running through testing. 

It is definitely something that I'll be keeping an eye on, since that change in CI 3 renamed (and repurposed?) that method.

**Pull request merged**
