### PR TITLE
Fix for HMVC form validation rules with callbacks.

### PR DESCRIPTION
**Pull request by IrcDirk**
Form validation rules with callbacks wasnt working in modules. Fix based on HMVC documentation.

### CODE REVIEW

**Comment by lonnieezell** [comment]
Were you running into problems with this? For some reason I was thinking this HMVC solution that I was using didn't hit the issue there? I could be wrong. It's been a few months since I investigated that.

**Comment by IrcDirk** [comment]
Model located in `APPPATH/modules/{module_name}/model/` and validation rule:

```
array(
            'field' => 'link',
            'label' => 'Link',
            'rules' => 'callback_check_link',
        )
```

and `public function check_link` was not called.

My fix makes it work.

**Comment by lonnieezell** [comment]
Ok, cool. Good enough for me. Wish there was a modular solution that didn't require these hacks. :) Merging.

**Comment by IrcDirk** [comment]
There is still a problem. This fix works for models loaded with `$this->load->model()` but not with BaseController auto load model variable `protected $model_file`

**Pull request merged**
