### PR TITLE
Some fixes for migrations and start of I18n class.

### PR DESCRIPTION
**Pull request by IrcDirk**
As my default engine was MyISAM and some tables couldnt be added because of too large index.

### CODE REVIEW

**Comment by IrcDirk** [comment]
Should cover all needs of https://github.com/ci-bonfire/Sprint/issues/69

**Comment by lonnieezell** [comment]
First off - thanks for tackling this project! 

A few changes I'd like to see: 
- The code you have in the i18n library currently is more appropriate to by in the MY_URI file, because, truly, it is simply a tweak to the existing library and not common i18n code that might be used in other places.
- Instead of modifying the existing `_set_uri_string()` method, I've made a couple of notes on that class as to why, but I think this can be more simply handled in `MY_URI::__construct()`. Once the CI_URI class has run through it's constructor, then it's already set the uri segments array, etc. So we can array_shift an item off the beginning of the array and check if it matches one of the items in the configured array of languages. This should call out to the i18n library since the logic to handle determining if it's a language, and mapping it from the 2-character ISO language code to our translation directory names is i18n specific and allows us to change the implementation later without issue. Also allows easier testing of the logic.
- If it does match a language, then it should define a constant value, i.e. `define('CURRENT_LANGUAGE', $lang);`. This makes it available everywhere in the system.

One thought/concern I just had, is whether `config_item` is avialble at that point. Looking at your code it looks like it might, but I didn't think it was available until later during the bootstrap process? Maybe that's just get_instance() I'm thinking of.

Once you have the logic/mapping moved into the i18n library, if you could provide some unit tests for that, also, that would be fantastic.

**Comment by IrcDirk** [comment]
Ok so, if im getting it right:
- create MY_URI.php
- call parent::constructor
- in construct call i18n library to shift segment, set constant, return new segments
  ?

As for config_item, yes it is available. The problem was with get_instance function, it didnt worked in MY_URI :/

**Comment by lonnieezell** [comment]
Yes, you have it right. Don't forget to deal with any two-character ISO langauge code mapping to the [url=https://github.com/bcit-ci/codeigniter3-translations]CodeIgniter Tranlsations[/url]. The constant should have the CI Translation code set, NOT the 2-character code, since any time we pull a language file, we'll need to pass that idiom into it to get the correct language. 

Just thinking - maybe we need to override the load->language to default to whatever language is defined in that constant also?

**Comment by IrcDirk** [comment]
A thougt about not to add all CItranslations to SprintPHP. User will add those which he wants and will set code mapping in i18n.languages:
[
'en' => 'english',
'de' => 'deutsh' 
]

Constat is allready mapped Ci translation code set no ISO.

**Comment by lonnieezell** [comment]
Oh, you're right! Doh! Then it's covered. 

And I didn't mean to add all of the actual translations, just needed ways to make sure we mapped up to that, but yes, I like mapping it that way. 

Sorry. Head in too many places currently. :)

**Comment by IrcDirk** [comment]
So maybe I18n should be extension (php extends) of core Language library?

**Comment by lonnieezell** [comment]
I'm having trouble seeing why it needs to extend the core Language library? Can you provide reasoning? 

My initial thought is that library is just to hold specific methods that we'll need for doing the i18n stuff. Not just this, but I'm sure there's other things. Can't think of them right now, of course. :)

**Pull request closed without merging**
